### PR TITLE
Verify SSL certs for urllib

### PR DESCRIPTION
**Pull request by spwoodcock**
Every odkcentral API results in `...site-packages/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'central-proxy'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings`

I changed verify=True to urllib.

Reject this PR if you can foresee issues doing that.
(I already handled this for the fmtm-api container having the necessary certs).

### CODE REVIEW

**Comment by robsavoye** [comment]
I had to add that since I've been developing using a local Central with a self-signed cert. If verify is True, I can't even connect to the server. I think this is temporary though, once the code is fully operational, it will be connecting to a real server instead of my local one. I get tired of that warning too.

**Comment by spwoodcock** [comment]
FMTM runs a version of Central including an self-signed cert too, but this shouldn't be problem, as the cert is installed in the trusted certificates for the backend dockerfile.

To solve the issue for a local version of Central, you can install your self-signed cert to the trusted certs on your system.
On Debian/Ubuntu it would be something like:
```bash
apt update
apt install ca-certificates
cp <your_cert_file> /usr/local/share/ca-certificates
update-ca-certificates
```

**Comment by robsavoye** [comment]
Since the self-signed cert  is in a docker container, where would I find it ?

**Comment by spwoodcock** [comment]
It's actually committed to the FMTM repo: https://github.com/hotosm/fmtm/blob/main/central_proxy/central-cert.pem
The cert is used to proxy odkcentral via nginx, and also installed in the fmtm backend container to verify ssl.

**Comment by robsavoye** [comment]
We should probably add something to the setup docs for developers about this so people don't have to access a closed PR.

**Pull request merged**
