### PR TITLE
Created a symlink for the README

### PR DESCRIPTION
**Pull request by mohammadareeb95**
A symlink is created so the homepage file serves as both the README and wiki landing page, avoiding content duplication.

Towards #81

### CODE REVIEW

**Comment by spwoodcock** [comment]
I renamed Homepage to Home.
My mistake, GitHub docs are a bit sparse.
The wiki home page works now.

The README still seems to load without issue.
@mohammadareeb95 is the symlink set correctly?
I couldn't check properly due to only having my phone.

**Comment by spwoodcock** [comment]
I just managed to check this - the symlink was never created, only a duplicate of the README.

Will fix in another PR.

**Comment by mohammadareeb95** [comment]
That's strange because I could see the symlink symbol in my editor and also when I ran `ls -l README.md docs/Homepage.md
` I can push this from scratch and apologies for the inconvenience.

**Comment by spwoodcock** [comment]
No worries @mohammadareeb95! I added the symlink in a new PR linked above, so no need - thanks!

**Pull request merged**
