### PR TITLE
Fix listProjects and findAppUser methods for OdkCentral

### PR DESCRIPTION
**Pull request by spwoodcock**

### CODE REVIEW

**Comment by robsavoye** [comment]
I think the change for logging needs to be in all the files, not just OdkCentral.py. Obviously the logging was setup for odkconvert running standalone, and not part of the FMTM backend.

**Comment by spwoodcock** [comment]
Sorry to pollute this PR with the logging update, I changed it as I wasn't receiving logs during debugging. 

I should have added the log update as a separate commit.

I will create an issue to update the logging throughout odkconvert and do it soon.

**Comment by spwoodcock** [comment]
I'll work out the conflicts and get this either merge-able or closed ASAP.

**Comment by spwoodcock** [comment]
I fixed the conflicts / merged changes together.

**Pull request merged**
